<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Lock_X</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>logoLockX.ico</ApplicationIcon>
    <Authors>CiMi131's Lab</Authors>
    <Version>26.0</Version>
    <Company>CiMi131's Lab</Company>
    <PackageIcon>logoLockX.png</PackageIcon>
    <StartupObject></StartupObject>
    <Title>Lock X</Title>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="logoLockX.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\..\..\Downloads\logoLockX.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Settings1.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings1.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Settings1.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings1.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>